### ISSUE TITLE
Normalize to all variables in [-1, 1]

### ISSUE THREAD

**Issue by dpsanders** [JuliaIntervals/TaylorModels.jl#30]
@mforets Do you have code for this?

**Comment by lbenet** [comment]
See https://github.com/JuliaDiff/TaylorSeries.jl/pull/195

**Comment by mforets** [comment]
@dpsanders It seems like github didn't really ping me since the question was added as an edit to the comment, sorry... Yes, @lbenet has taken the lead on that aspect and added the multi-dimensional case as well.

What is the plan for the normalization of a TaylorModel? To normalize the interval of interest and the polynomial approx? Can it reuse some of the new code in TaylorSeries?

**Comment by lbenet** [comment]
> What is the plan for the normalization of a TaylorModel? To normalize the interval of interest and the polynomial approx? Can it reuse some of the new code in TaylorSeries?

The way I have used it in #18, essentially you normalize first the polynomial and then define the corresponding `TaylorModel` with the proper parameters. See lines 92-96 of `src/validatedODEs.jl`.

**Comment by lbenet** [comment]
I am closing this since it was already answered.

Yet, I'd like to point out that the issue of "normalize or not normalize" is addressed in the benchmarks.
